go_import_path: github.com/paultyng/go-newrelic

language: go
go:
  - 1.11.x
  - 1.12.x
  - tip

os:
  - linux
  - osx

matrix:
  allow_failures:
    - go: tip
    - os: osx
  fast_finish: true

env:
  GO111MODULE: 'on'

install:
  - go mod download
  - go mod verify

script:
  - go install
  - go test -v -cover ./...

sudo: false
