/* 
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package newrelic-api

type MobileSummaryDataResponse struct {

	ActiveUsers int32 `json:"active_users,omitempty"`

	LaunchCount int32 `json:"launch_count,omitempty"`

	Throughput float32 `json:"throughput,omitempty"`

	ResponseTime float32 `json:"response_time,omitempty"`

	CallsPerSession float32 `json:"calls_per_session,omitempty"`

	InteractionTime float32 `json:"interaction_time,omitempty"`

	FailedCallRate float32 `json:"failed_call_rate,omitempty"`

	RemoteErrorRate float32 `json:"remote_error_rate,omitempty"`
}
