/* 
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package newrelic-api

type NotificationChannelResponseType struct {

	Id int32 `json:"id,omitempty"`

	Type_ string `json:"type,omitempty"`

	DowntimeOnly bool `json:"downtime_only,omitempty"`

	Url string `json:"url,omitempty"`

	Name string `json:"name,omitempty"`

	Description string `json:"description,omitempty"`

	Email string `json:"email,omitempty"`

	Subdomain string `json:"subdomain,omitempty"`

	Service string `json:"service,omitempty"`

	MobileAlerts bool `json:"mobile_alerts,omitempty"`

	EmailAlerts bool `json:"email_alerts,omitempty"`

	Room string `json:"room,omitempty"`

	Links NotificationChannelLinksResponse `json:"links,omitempty"`
}
