/* 
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package newrelic-api

type PluginDetailsResponse struct {

	Description int32 `json:"description,omitempty"`

	IsPublic string `json:"is_public,omitempty"`

	CreatedAt Time `json:"created_at,omitempty"`

	UpdatedAt Time `json:"updated_at,omitempty"`

	LastPublishedAt Time `json:"last_published_at,omitempty"`

	HasUnpublishedChanges bool `json:"has_unpublished_changes,omitempty"`

	BrandingImageUrl string `json:"branding_image_url,omitempty"`

	UpgradedAt Time `json:"upgraded_at,omitempty"`

	ShortName string `json:"short_name,omitempty"`

	PublisherAboutUrl string `json:"publisher_about_url,omitempty"`

	PublisherSupportUrl string `json:"publisher_support_url,omitempty"`

	DownloadUrl string `json:"download_url,omitempty"`

	FirstEditedAt Time `json:"first_edited_at,omitempty"`

	LastEditedAt Time `json:"last_edited_at,omitempty"`

	FirstPublishedAt Time `json:"first_published_at,omitempty"`

	PublishedVersion string `json:"published_version,omitempty"`
}
