/* 
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package newrelic-api

type RecentEventResponseType struct {

	Id int32 `json:"id,omitempty"`

	EventType string `json:"event_type,omitempty"`

	Product string `json:"product,omitempty"`

	EntityType string `json:"entity_type,omitempty"`

	EntityGroupId int32 `json:"entity_group_id,omitempty"`

	EntityId int32 `json:"entity_id,omitempty"`

	Priority string `json:"priority,omitempty"`

	Description string `json:"description,omitempty"`

	Timestamp int32 `json:"timestamp,omitempty"`

	IncidentId int32 `json:"incident_id,omitempty"`
}
