/* 
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package newrelic-api

type ServerSummaryResponse struct {

	Cpu float32 `json:"cpu,omitempty"`

	CpuStolen float32 `json:"cpu_stolen,omitempty"`

	DiskIo float32 `json:"disk_io,omitempty"`

	Memory float32 `json:"memory,omitempty"`

	MemoryUsed int32 `json:"memory_used,omitempty"`

	MemoryTotal int32 `json:"memory_total,omitempty"`

	FullestDisk float32 `json:"fullest_disk,omitempty"`

	FullestDiskFree int32 `json:"fullest_disk_free,omitempty"`
}
