/* 
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package newrelic-api

type UserResponseType struct {

	Id int32 `json:"id,omitempty"`

	Email string `json:"email,omitempty"`

	FirstName string `json:"first_name,omitempty"`

	LastName string `json:"last_name,omitempty"`

	State string `json:"state,omitempty"`

	ActivationCode string `json:"activation_code,omitempty"`

	ActivatedAt Datetime `json:"activated_at,omitempty"`

	IsNewrelicAdmin bool `json:"is_newrelic_admin,omitempty"`

	TimeZone string `json:"time_zone,omitempty"`

	SalesforceId string `json:"salesforce_id,omitempty"`

	DefaultAccountId int32 `json:"default_account_id,omitempty"`
}
