/* 
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package newrelic-api

type ViolationResponseType struct {

	Id int32 `json:"id,omitempty"`

	Label string `json:"label,omitempty"`

	Duration int32 `json:"duration,omitempty"`

	PolicyName string `json:"policy_name,omitempty"`

	ConditionName string `json:"condition_name,omitempty"`

	Priority string `json:"priority,omitempty"`

	OpenedAt int32 `json:"opened_at,omitempty"`

	ClosedAt int32 `json:"closed_at,omitempty"`

	Entity ViolationEntityResponse `json:"entity,omitempty"`

	Links ViolationLinksResponse `json:"links,omitempty"`
}
